### ISSUE TITLE
Updated and new publications on using AMX for cryptography

### ISSUE THREAD

**Issue by dgazzoni** [corsix/amx#12]
This is a followup on #9.

Our paper mentioned there was published in the the first edition of the new IACR Communications in Cryptology journal, so I'd like to ask if you'd be so kind as to update the link to the actual [journal paper](https://cic.iacr.org/p/1/1/9), I'd be grateful. We note that the repository associated with this paper is [now online](https://github.com/dgazzoni/NTRU-AMX), so you might be interested in linking to that as well.

Finally, we have [another paper out](https://eprint.iacr.org/2024/195) on implementing two other post-quantum cryptosystems on AMX. You may also be interested in adding a link to it.

Thanks.

**Comment by lin72h** [comment]
wow, that's impressive deep research, thanks for sharing

**Comment by corsix** [comment]
Done in [42a391b](https://github.com/corsix/amx/commit/42a391b9b77c9191fd8b8fa39b05e5f67cb6bd48).
